apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
secretGenerator:
- name: keycloak-db-secret
  namespace: keycloak
  literals:
  - POSTGRES_DATABASE=keycloak
  - POSTGRES_EXTERNAL_ADDRESS=postgres.keycloak.svc.cluster.local
  - POSTGRES_EXTERNAL_PORT=5432
  - POSTGRES_PASSWORD=psqlpwd
  - POSTGRES_USERNAME=postgres
  type: Opaque
  options:
    labels:
      app: sso
generatorOptions:
  annotations:
    psql.usage/app1: keycloak
  disableNameSuffixHash: true
resources:
- keycloak.yaml
