apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
secretGenerator:
- name: tls-secret
  namespace: ingress-nginx
  files:
  - tls.crt=sslcerts/localhost.crt
  - tls.key=sslcerts/localhost.decrypted.key
  type: "kubernetes.io/tls"
generatorOptions:
  labels:
    app: nginx-ingress
  disableNameSuffixHash: true
resources:
- nginx-ingress-1.1.0.yaml
#- ambassador-tls.yaml
