apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
secretGenerator:
- name: postgres-config-secret
  namespace: keycloak
  literals:
  - password=psqlpwd
  type: Opaque
  options:
    labels:
      app: postgres
generatorOptions:
  annotations:
    psql.usage/app1: keycloak
  disableNameSuffixHash: true
resources:
- namespace.yaml
- psql-storage.yaml
- psql-deployment.yaml
- psql-service.yaml
