---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/local-path-provisioner/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: postgres
    type: local
spec:
  volumeName: psql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
